v {xschem version=3.4.8RC file_version=1.3}
G {}
K {}
V {}
S {}
F {}
E {}
B 2 -2760 560 -1960 960 {flags=graph
y1=0.66875437
y2=0.69818539
ypos1=-0.11
ypos2=2
divy=5
subdivy=4
unity=1
x1=4.3066451e-06
x2=4.9079404e-06
divx=5
subdivx=1
xlabmag=1.0
ylabmag=1.0


dataset=-1
unitx=1
logx=0
logy=0

digital=0


sim_type=tran




color="4 5"
node="x1.vdac_p
x1.vdac_n"}
B 2 -1930 560 -1130 960 {flags=graph
y1=0
y2=2
ypos1=0
ypos2=2
divy=5
subdivy=1
unity=1
x1=4.4870339e-06
x2=5.0883292e-06
divx=5
subdivx=1
xlabmag=1.0
ylabmag=1.0
node="clk_data
result;data[5],data[4],data[3],data[2],data[1],data[0]
start"
color="8 6 7"
dataset=-1
unitx=1
logx=0
logy=0
digital=1}
B 2 -2760 980 -1960 1380 {flags=graph
y1=0.013
y2=1.5
ypos1=1.7
ypos2=1.9
divy=5
subdivy=4
unity=1
x1=4.3066451e-06
x2=4.9079404e-06
divx=5
subdivx=1
xlabmag=1.0
ylabmag=1.0


dataset=-1
unitx=1
logx=0
logy=0

digital=0


sim_type=tran


color="4 5"
node="x1.vdac_pi
x1.vdac_ni"}
N -2460 20 -2460 40 {
lab=#net1}
N -2380 20 -2380 40 {
lab=#net2}
N -2300 20 -2300 40 {
lab=#net3}
N -2540 260 -2540 280 {
lab=#net4}
N -2360 260 -2360 280 {
lab=#net5}
C {SAR_ADC_12BIT.sym} -2090 350 0 0 {name=x1}
C {devices/lab_wire.sym} -1540 80 0 0 {name=p1 sig_type=std_logic lab=VDD}
C {devices/lab_wire.sym} -1540 260 2 1 {name=p3 sig_type=std_logic lab=VSS}
C {devices/vsource.sym} -2540 70 0 0 {name=V1 value=\{VDD\} savecurrent=true}
C {devices/lab_wire.sym} -2540 100 2 1 {name=p11 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} -2540 40 0 0 {name=p12 sig_type=std_logic lab=VDD}
C {devices/vsource.sym} -2460 70 0 0 {name=V2 value=\{VCM\} savecurrent=true}
C {devices/lab_wire.sym} -2460 100 2 1 {name=p13 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} -2460 -40 0 0 {name=p14 sig_type=std_logic lab=VCM}
C {devices/vsource.sym} -2380 70 0 0 {name=V3 value=\{VREF\} savecurrent=true}
C {devices/lab_wire.sym} -2380 100 2 1 {name=p15 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} -2380 -40 0 0 {name=p16 sig_type=std_logic lab=VREF}
C {devices/vsource.sym} -2220 70 0 0 {name=V4 value=0 savecurrent=false}
C {devices/lab_wire.sym} -2220 100 2 1 {name=p17 sig_type=std_logic lab=GND}
C {devices/lab_wire.sym} -2220 40 0 0 {name=p18 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} -2540 340 2 1 {name=p19 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} -2540 200 0 0 {name=p20 sig_type=std_logic lab=VIN_P}
C {devices/lab_wire.sym} -2360 340 2 1 {name=p21 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} -2360 200 0 0 {name=p22 sig_type=std_logic lab=VIN_N}
C {devices/vsource.sym} -2140 310 0 0 {name=V7 value="pulse(0 \{VDD\} 200n 1n 1n 120n 2u)" savecurrent=false}
C {devices/lab_wire.sym} -2140 340 2 1 {name=p23 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} -2140 280 0 0 {name=p24 sig_type=std_logic lab=START}
C {devices/vsource.sym} -2140 70 0 0 {name=V8 value="pwl(
+ 0      0
+ 50n    0
+ 50.1n  \{VDD\}
)" savecurrent=false}
C {devices/lab_wire.sym} -2140 100 2 1 {name=p25 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} -2140 40 0 0 {name=p26 sig_type=std_logic lab=RST_Z}
C {devices/code.sym} -2770 220 0 0 {name=TT_MODELS
only_toplevel=true
format="tcleval(@value )"
value="

* Models for standard digital cells
.include $PDK_ROOT/ihp-sg13g2/libs.ref/sg13g2_stdcell/spice/sg13g2_stdcell.spice

* Spice netlist for state machine generated by openlane
.include $HOME/SAR_ADC_12bit_ihp/schematic/state_machine/state_machine.spice
"
spice_ignore=false
place=header}
C {devices/launcher.sym} -2700 -60 0 0 {name=h2 
descr="Simulate" 
tclcommand="xschem netlist; xschem simulate"}
C {devices/code.sym} -2776.41357421875 24.92919921875 0 0 {name=NGSPICE
only_toplevel=true
value="
* Supply, common mode and reference voltage
.param VDD = 1.2
.param VREF = 1
.param VREF_GND = 0
.param VCM = 0.5

.option temp = 27

*.save all

* Control signals
.save start rst_z clk en_offset_cal

* Input signals
.save vin_p vin_n

* Reference, supply
.save vref vref_gnd vcm vdd

* Output signals
.save clk_data data[5] data[4] data[3] data[2] data[1] data[0]

* Internal signals
.save x1.vdac_p x1.vdac_n x1.vdac_pi x1.vdac_ni x1.smpl x1.en_comp x1.comp_p x1.comp_n x1.cal_p x1.cal_n
.save x1.en_vin_bstr_p x1.en_vin_bstr_n
.save x1.c10_p_btm x1.c9_p_btm x1.c8_p_btm x1.c7_p_btm x1.c6_p_btm x1.c5_p_btm x1.c4_p_btm x1.c3_p_btm x1.c2_p_btm x1.c1_p_btm x1.c0_p_btm x1.C0_dummy_p_btm
.save x1.c10_n_btm x1.c9_n_btm x1.c8_n_btm x1.c7_n_btm x1.c6_n_btm x1.c5_n_btm x1.c4_n_btm x1.c3_n_btm x1.c2_n_btm x1.c1_n_btm x1.c0_n_btm x1.C0_dummy_n_btm

.option GMIN=1e-12 reltol=1e-5
.control
		set ngbehavior=hsa
          	set ng_nomodcheck
  		set num_threads=4
  		option noinit
  		option klu
		tran 10n 8u
		write top_level_differential_sim1.raw
.endc
"}
C {devices/vsource.sym} -2540 310 0 0 {name=V5 value="pwl(
+ 0.000u 0.5
+ 1.000u 0.5
+ 1.001u 0.35
+ 2.000u 0.35
+ 2.001u 0.65
+ 3.000u 0.65
+ 3.001u 0.80
+ 4.000u 0.80
+ 4.001u 0.20
+ 5.000u 0.20
+ 5.001u 0.05
+ 6.000u 0.05
+ 6.001u 0.95
+ 7.000u 0.95
)" savecurrent=false}
C {devices/res.sym} -2460 -10 2 0 {name=R1
value=500
footprint=1206
device=resistor
m=1}
C {devices/vsource.sym} -2140 190 0 0 {name=V9 value="pulse(0 \{VDD\} 0 1n 1n 60n 120n)" savecurrent=false}
C {devices/lab_wire.sym} -2140 220 2 1 {name=p30 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} -2140 160 0 0 {name=p31 sig_type=std_logic lab=CLK}
C {devices/lab_pin.sym} -1820 160 0 0 {name=p37 lab=VIN_P}
C {devices/lab_pin.sym} -1820 180 0 0 {name=p38 lab=VIN_N}
C {devices/lab_pin.sym} -1820 120 0 0 {name=p39 lab=RST_Z}
C {devices/lab_pin.sym} -1480 160 0 1 {name=p40 lab=CLK_DATA}
C {devices/lab_pin.sym} -1480 180 0 1 {name=p41 lab=DATA[5:0]}
C {devices/lab_pin.sym} -1820 140 0 0 {name=p42 lab=START}
C {devices/lab_pin.sym} -1820 200 0 0 {name=p43 lab=EN_OFFSET_CAL}
C {devices/lab_pin.sym} -1820 100 0 0 {name=p44 lab=CLK}
C {devices/lab_pin.sym} -1820 220 0 0 {name=p46 lab=SINGLE_ENDED}
C {devices/lab_wire.sym} -1660 260 2 1 {name=p33 sig_type=std_logic lab=VREF_GND}
C {devices/lab_wire.sym} -1620 80 0 0 {name=p8 sig_type=std_logic lab=VCM}
C {devices/lab_wire.sym} -1660 80 0 0 {name=p9 sig_type=std_logic lab=VREF}
C {devices/vsource.sym} -2360 310 0 0 {name=V6 value="pwl(
+ 0.000u 0.5
+ 1.000u 0.5
+ 1.001u 0.65
+ 2.000u 0.65
+ 2.001u 0.35
+ 3.000u 0.35
+ 3.001u 0.20
+ 4.000u 0.20
+ 4.001u 0.80
+ 5.000u 0.80
+ 5.001u 0.95
+ 6.000u 0.95
+ 6.001u 0.05
+ 7.000u 0.05
)" savecurrent=false}
C {devices/vsource.sym} -2300 70 0 0 {name=V10 value=\{VREF_GND\} savecurrent=true}
C {devices/lab_wire.sym} -2300 100 2 1 {name=p7 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} -2300 -40 0 0 {name=p10 sig_type=std_logic lab=VREF_GND}
C {devices/res.sym} -2380 -10 2 0 {name=R6
value=500
footprint=1206
device=resistor
m=1}
C {devices/res.sym} -2300 -10 2 0 {name=R7
value=500
footprint=1206
device=resistor
m=1}
C {devices/res.sym} -2540 230 2 0 {name=R8
value=500
footprint=1206
device=resistor
m=1}
C {devices/res.sym} -2360 230 2 0 {name=R9
value=500
footprint=1206
device=resistor
m=1}
C {devices/lab_wire.sym} -2540 -120 2 1 {name=p2 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} -2540 -180 0 0 {name=p4 sig_type=std_logic lab=EN_OFFSET_CAL}
C {devices/vsource.sym} -2540 -150 0 0 {name=V11 value="pwl(
+ 0      0
+ 5u     0
+ 5.001u \{VDD\}
)" savecurrent=false}
C {devices/lab_wire.sym} -2300 -120 2 1 {name=p5 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} -2300 -180 0 0 {name=p6 sig_type=std_logic lab=SINGLE_ENDED}
C {devices/vsource.sym} -2300 -150 0 0 {name=V12 value=0 savecurrent=false}
C {devices/launcher.sym} -2690 520 0 0 {name=h5
descr="Load Waveforms" 
tclcommand="xschem raw_read $netlist_dir/top_level_differential_sim.raw tran"
}
