v {xschem version=3.4.8RC file_version=1.3}
G {}
K {}
V {}
S {}
F {}
E {}
N 230 570 250 570 {
lab=RST_Z}
N 230 590 250 590 {
lab=START}
N 550 590 570 590 {
lab=CLK_DATA}
N 550 570 570 570 {
lab=DATA[5:0]}
N 230 610 250 610 {
lab=EN_OFFSET_CAL}
N 230 910 250 910 {
lab=CLK}
N 230 630 250 630 {
lab=SINGLE_ENDED}
N 1450 1130 1450 1150 {
lab=#net1}
N 1530 1130 1530 1150 {
lab=#net2}
N 1610 1130 1610 1150 {
lab=#net3}
N 1370 1370 1370 1390 {
lab=#net4}
N 1550 1370 1550 1390 {
lab=#net5}
C {devices/lab_pin.sym} 250 670 0 0 {name=p177 sig_type=std_logic lab=COMP_P}
C {devices/lab_pin.sym} 550 690 0 1 {name=p181 sig_type=std_logic lab=EN_VCM[10:0]}
C {devices/lab_pin.sym} 550 910 0 1 {name=p189 sig_type=std_logic lab=EN_COMP}
C {devices/lab_pin.sym} 550 650 0 1 {name=p191 sig_type=std_logic lab=SMPL}
C {devices/lab_pin.sym} 250 730 0 0 {name=p231 sig_type=std_logic lab=SMPL_ON_P}
C {devices/lab_pin.sym} 250 750 0 0 {name=p256 sig_type=std_logic lab=SMPL_ON_N}
C {devices/lab_wire.sym} 400 1090 2 0 {name=p76 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 400 540 0 1 {name=p171 sig_type=std_logic lab=VDD}
C {devices/ipin.sym} 230 570 0 0 {name=p172 lab=RST_Z}
C {devices/ipin.sym} 230 590 0 0 {name=p173 lab=START}
C {devices/opin.sym} 570 590 0 0 {name=p174 lab=CLK_DATA}
C {devices/lab_pin.sym} 550 950 0 1 {name=p201 sig_type=std_logic lab=OFFSET_CAL_CYCLE}
C {devices/lab_pin.sym} 550 970 0 1 {name=p219 sig_type=std_logic lab=EN_VOS_CAL}
C {devices/opin.sym} 570 570 0 0 {name=p4 lab=DATA[5:0]}
C {devices/lab_pin.sym} 550 730 0 1 {name=p132 sig_type=std_logic lab=EN_VCM_SW}
C {devices/lab_pin.sym} 550 710 0 1 {name=p131 sig_type=std_logic lab=EN_VCM_DUMMY}
C {devices/lab_pin.sym} 550 830 0 1 {name=p134 lab=EN_VSS_N[10:0]}
C {devices/lab_pin.sym} 550 810 0 1 {name=p135 lab=EN_REF_Z_N[10:0]}
C {devices/ipin.sym} 230 610 0 0 {name=p11 lab=EN_OFFSET_CAL}
C {devices/ipin.sym} 230 910 0 0 {name=p15 lab=CLK}
C {devices/lab_pin.sym} 250 970 0 0 {name=p23 sig_type=std_logic lab=EN_VCM_SW}
C {devices/lab_pin.sym} 250 990 0 0 {name=p24 sig_type=std_logic lab=EN_VCM[10:0]}
C {devices/lab_pin.sym} 550 790 0 1 {name=p31 lab=EN_VSS_P_BBM[10:0]}
C {devices/lab_pin.sym} 550 770 0 1 {name=p32 lab=EN_REF_Z_P_BBM[10:0]}
C {devices/ipin.sym} 230 630 0 0 {name=p9 lab=SINGLE_ENDED}
C {devices/code_shown.sym} 1260 240 0 0 {name=TT_MODELS
only_toplevel=true
format="tcleval(@value )"
value="

* Models for standard digital cells
.include $PDK_ROOT/ihp-sg13g2/libs.ref/sg13g2_stdcell/spice/sg13g2_stdcell.spice

* Spice netlist for state machine generated by openlane
.include $HOME/schematic/state_machine/state_machine.spice
"
spice_ignore=false
place=header}
C {devices/launcher.sym} 1080 70 0 0 {name=h2 
descr="Simulate" 
tclcommand="xschem netlist; xschem simulate"}
C {devices/code_shown.sym} 1283.58642578125 484.92919921875 0 0 {name=NGSPICE
only_toplevel=true
value="
* Supply, common mode and reference voltage
.param VDD = 1.2
.param VREF = 1
.param VREF_GND = 0
.param VCM = 0.5

.option temp = 27


.option GMIN=1e-12 reltol=1e-5
.control
		
		tran 10n 8u
	
.endc
"}
C {devices/code_shown.sym} 1290 50 0 0 {name=MODEL1 only_toplevel=true
format="tcleval( @value )"
value=".lib cornerMOSlv.lib mos_tt
.lib cornerMOShv.lib mos_tt
.lib $::SG13G2_MODELS/cornerRES.lib res_typ_stat

"}
C {devices/vsource.sym} 1370 1180 0 0 {name=V13 value=\{VDD\} savecurrent=true}
C {devices/lab_wire.sym} 1370 1210 2 1 {name=p1 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 1370 1150 0 0 {name=p12 sig_type=std_logic lab=VDD}
C {devices/vsource.sym} 1450 1180 0 0 {name=V14 value=\{VCM\} savecurrent=true}
C {devices/lab_wire.sym} 1450 1210 2 1 {name=p13 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 1450 1070 0 0 {name=p14 sig_type=std_logic lab=VCM}
C {devices/vsource.sym} 1530 1180 0 0 {name=V15 value=\{VREF\} savecurrent=true}
C {devices/lab_wire.sym} 1530 1210 2 1 {name=p2 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 1530 1070 0 0 {name=p16 sig_type=std_logic lab=VREF}
C {devices/vsource.sym} 1690 1180 0 0 {name=V16 value=0 savecurrent=false}
C {devices/lab_wire.sym} 1690 1210 2 1 {name=p17 sig_type=std_logic lab=GND}
C {devices/lab_wire.sym} 1690 1150 0 0 {name=p18 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 1370 1450 2 1 {name=p19 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 1370 1310 0 0 {name=p20 sig_type=std_logic lab=VIN_P}
C {devices/lab_wire.sym} 1550 1450 2 1 {name=p21 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 1550 1310 0 0 {name=p22 sig_type=std_logic lab=VIN_N}
C {devices/vsource.sym} 1770 1420 0 0 {name=V17 value="pulse(0 \{VDD\} 20n 1n 1n 100n 1u)" savecurrent=false}
C {devices/lab_wire.sym} 1770 1450 2 1 {name=p3 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 1770 1390 0 0 {name=p5 sig_type=std_logic lab=START}
C {devices/vsource.sym} 1770 1180 0 0 {name=V18 value="pwl(0 0 10n 0 10.1n \{VDD\})" savecurrent=false}
C {devices/lab_wire.sym} 1770 1210 2 1 {name=p6 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 1770 1150 0 0 {name=p26 sig_type=std_logic lab=RST_Z}
C {devices/launcher.sym} 1210 1050 0 0 {name=h1 
descr="Simulate" 
tclcommand="xschem netlist; xschem simulate"}
C {devices/vsource.sym} 1370 1420 0 0 {name=V19 value="pwl(0.000u 0.6 1u 0.6
+ 1.000u 0.4000 2u 0.4000
+ 2.001u 0.8000 3u 0.8000
+ 3.001u 0.9599 4u 0.9599
+ 4.001u 0.2401 5u 0.2401
+ 5.001u 0.0186 6u 0.0186
+ 6.001u 1.1814 7u 1.1814)" savecurrent=false}
C {devices/res.sym} 1450 1100 2 0 {name=R2
value=500
footprint=1206
device=resistor
m=1}
C {devices/vsource.sym} 1770 1300 0 0 {name=V20 value="pulse(0 \{VDD\} 0 1n 1n 40n 50n)" savecurrent=false}
C {devices/lab_wire.sym} 1770 1330 2 1 {name=p30 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 1770 1270 0 0 {name=p7 sig_type=std_logic lab=CLK}
C {devices/vsource.sym} 1550 1420 0 0 {name=V21 value="pwl(0.000u 0.6 1u 0.6
+ 1.000u 0.8000 2u 0.8000
+ 2.001u 0.4000 3u 0.4000
+ 3.001u 0.2401 4u 0.2401
+ 4.001u 0.9599 5u 0.9599
+ 5.001u 1.1814 6u 1.1814
+ 6.001u 0.0186 7u 0.0186)" savecurrent=false}
C {devices/vsource.sym} 1610 1180 0 0 {name=V22 value=\{VREF_GND\} savecurrent=true}
C {devices/lab_wire.sym} 1610 1210 2 1 {name=p8 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 1610 1070 0 0 {name=p27 sig_type=std_logic lab=VREF_GND}
C {devices/res.sym} 1530 1100 2 0 {name=R3
value=500
footprint=1206
device=resistor
m=1}
C {devices/res.sym} 1610 1100 2 0 {name=R4
value=500
footprint=1206
device=resistor
m=1}
C {devices/res.sym} 1370 1340 2 0 {name=R5
value=500
footprint=1206
device=resistor
m=1}
C {devices/res.sym} 1550 1340 2 0 {name=R10
value=500
footprint=1206
device=resistor
m=1}
C {devices/lab_wire.sym} 1370 990 2 1 {name=p28 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 1370 930 0 0 {name=p29 sig_type=std_logic lab=EN_OFFSET_CAL}
C {devices/vsource.sym} 1370 960 0 0 {name=V23 value="pwl(0 0 3u 0 3.001u \{VDD\})" savecurrent=false}
C {devices/lab_wire.sym} 1610 990 2 1 {name=p33 sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 1610 930 0 0 {name=p34 sig_type=std_logic lab=SINGLE_ENDED}
C {devices/vsource.sym} 1610 960 0 0 {name=V24 value=0 savecurrent=false}
C {state_machine/state_machine.sym} 430 680 0 0 {name=x1}
